### ISSUE TITLE
Unable to silence the warning "a promise was created in a handler but none were returned from it"

### ISSUE THREAD

**Issue by MaximilianLloyd** [petkaantonov/bluebird#1027]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on? The latest, 3.3.3
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32) 4.3.1
3) Did this issue happen with earlier version of bluebird? Yes

I am using sequelize. The reason i am placing the issue here is because that the error itself comes from bluebird. I have looked through the warning explanations to silence the warning but to no avail. Please look at the screen shot below:

![skjermbilde](https://cloud.githubusercontent.com/assets/10583205/13379806/d086748e-de30-11e5-84a5-9ebac9a99f6c.PNG)

stack trace: 
`Warning: a promise was created in a handler but was not returned from it
    at [object Object].Model.findAll (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\sequelize\lib\model.js:1343:18)
    at C:/Users/maxll/Desktop/poker.no-mobile/server/components/sequel/index.js:14:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.then (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\sequelize\lib\promise.js:21:17)
    at Object.<anonymous> (C:/Users/maxll/Desktop/poker.no-mobile/server/components/sequel/index.js:11:18)
    at Module._compile (module.js:409:26)
    at normalLoader (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/maxll/Desktop/poker.no-mobile/server/api/user/user.model.js:3:46)
    at Module._compile (module.js:409:26)
    at normalLoader (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/maxll/Desktop/poker.no-mobile/server/api/user/user.controller.js:1:14)
    at Module._compile (module.js:409:26)
    at normalLoader (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/maxll/Desktop/poker.no-mobile/server/api/user/index.js:3:31)
    at Module._compile (module.js:409:26)
    at normalLoader (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\maxll\Desktop\poker.no-mobile\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)`

**Comment by benjamingr** [comment]
The warning is correct and bluebird most likely found an issue with your code.

You are calling `User.findAll` inside a `then` handler but not returning it or its aggregation - when it fails you do not react to it failing - it does not affect the chain.

You can collect the `User.findAll` calls and `return` their aggregation with `.all`.

**Comment by MaximilianLloyd** [comment]
Ok thank you. Fixed now.

**Comment by waynebloss** [comment]
I am having the same problem.

```
Warning: a promise was created in a handler at domain.js:126:23 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/a/bitbean/ta/api/node_modules/bluebird/js/release/promise.js:196:13)
```

Where do you put the `.all` here?

```js
const getSeries = async (req, res, next) => {
  const limit = req.swagger.params.limit.value || 5;
  const offset = req.swagger.params.offset.value || 0;
  const allSeries = await series
    .findAll({
      limit,
      offset,
    })
    .catch(next);
  res.json(allSeries);
};
```

I tried it between `.findAll()` and `.catch()`. I tried removing the `async/await` and using a `.then()`.
