### ISSUE TITLE
Custom Errors Throw 'a promise was rejected with a non-error'

### ISSUE THREAD

**Issue by devotox** [petkaantonov/bluebird#1037]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.3.4

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Docker Node 5.7.0/ Google chrome

3) Did this issue happen with earlier version of bluebird?
Yes
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

```
======== API ERROR =======(anonymous function) @ application.js:54mightThrow @ jquery.js:3454process @ jquery.js:3523
bluebird.js:1472 Warning: a promise was rejected with a non-error: [object Object]
    at Object.<anonymous> (https://www.intranet.doctify.local.com/assets/doctify.js:500:6)
    at mightThrow (https://www.intranet.doctify.local.com/assets/vendor.js:3681:29)
    at process (https://www.intranet.doctify.local.com/assets/vendor.js:3750:12)
From previous event:
    at api (https://www.intranet.doctify.local.com/assets/doctify.js:483:11)
    at postForm (https://www.intranet.doctify.local.com/assets/doctify.js:2931:18)
    at submit (https://www.intranet.doctify.local.com/assets/doctify.js:2924:10)
    at Object.triggerEvent (https://www.intranet.doctify.local.com/assets/vendor.js:38839:35)
    at Object.trigger (https://www.intranet.doctify.local.com/assets/vendor.js:63413:14)
    at Object.Router.trigger (https://www.intranet.doctify.local.com/assets/vendor.js:62172:20)
    at _emberRuntimeSystemObject.default.extend.send (https://www.intranet.doctify.local.com/assets/vendor.js:38310:40)
    at _emberMetalMixin.Mixin.create.send (https://www.intranet.doctify.local.com/assets/vendor.js:42954:33)
    at runRegisteredAction (https://www.intranet.doctify.local.com/assets/vendor.js:39865:25)
    at Object.Backburner.run (https://www.intranet.doctify.local.com/assets/vendor.js:10882:25)
    at Object.run [as default] (https://www.intranet.doctify.local.com/assets/vendor.js:31438:27)
    at Object.actions.push.handler (https://www.intranet.doctify.local.com/assets/vendor.js:39859:36)
    at HTMLFormElement.<anonymous> (https://www.intranet.doctify.local.com/assets/vendor.js:54645:27)
    at HTMLBodyElement.jQuery.event.dispatch (https://www.intranet.doctify.local.com/assets/vendor.js:5272:27)
    at HTMLBodyElement.elemData.handle (https://www.intranet.doctify.local.com/assets/vendor.js:5084:28)
application.js:56 Object {readyState: 4, responseText: "Invalid account name or password.", status: 400, statusText: "OK"} APIError {message: Object, name: "APIError"}

```

```

		function APIError(message) {
		   Error.captureStackTrace(this);
		   this.message = message;
		   this.name = "APIError";
		}
		APIError.prototype = Object.create(Error.prototype);
reject(new APIError(error));
```

Throwning a custom error gives the `a promise was rejected with a non-error` deprecation warning and the message is not passed in the reject

**Comment by petkaantonov** [comment]
is `message` a string? It should be `this.message = message + ""`

**Comment by devotox** [comment]
ha only strings allowed. Gotcha
