### ISSUE TITLE
I still get this error even after update 'Warning: a promise was created in a handler but was not returned from it'

### ISSUE THREAD

**Issue by devotox** [petkaantonov/bluebird#1038]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.3.4
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node 5.7.1 / Docker Node
3) Did this issue happen with earlier version of bluebird?
Yes
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I get this error when i do something like

```
promise.resolve(result).then(function(result){
			var _code = ( result && result.code ) || response_status.internal_success;
			return response.status(_code).json( ( result && result.response ) || result || []);
		}).catch(function(result){
			var _code = ( result && result.code ) || response_status.internal_error;
			return !response.headersSent ? response.status(_code).send(get_error_message(_code)) : get_error_message(_code);
		});
```

and even a return before the promise.resolve gives me nothing
Stack trace
```
api_1             | [ Nodemon ][ Error ] Warning: a promise was created in a handler but was not returned from it
api_1             |     at Object.__default__ (/var/app/current/api/common/utils/api_response_handler.js:181:18)
api_1             |     at Object.exports.switch_case (/var/app/current/api/common/utils/utils.js:77:51)
api_1             |     at Seneca.<anonymous> (/var/app/current/api/common/utils/api_response_handler.js:215:17)
api_1             |     at act_done (/var/app/current/api/node_modules/seneca/seneca.js:1220:21)
api_1             |     at /var/app/current/api/node_modules/gate-executor/gate-executor.js:155:20
api_1             |     at /var/app/current/api/common/utils/api_response_handler.js:262:12
api_1             |     at processImmediate [as _immediateCallback] (timers.js:383:17)
api_1             | From previous event:
api_1             |     at Object.__default__ (/var/app/current/api/common/utils/api_response_handler.js:257:27)
api_1             |     at Object.exports.switch_case (/var/app/current/api/common/utils/utils.js:77:51)
api_1             |     at null.callback (/var/app/current/api/common/utils/api_response_handler.js:322:18)
api_1             |     at Query.handleReadyForQuery (/var/app/current/api/node_modules/pg/lib/query.js:89:10)
api_1             |     at null.<anonymous> (/var/app/current/api/node_modules/pg/lib/client.js:163:19)
api_1             |     at emitOne (events.js:95:20)
api_1             |     at emit (events.js:182:7)
api_1             |     at Socket.<anonymous> (/var/app/current/api/node_modules/pg/lib/connection.js:109:12)
api_1             |     at emitOne (events.js:90:13)
api_1             |     at Socket.emit (events.js:182:7)
api_1             |     at readableAddChunk (_stream_readable.js:153:18)
api_1             |     at Socket.Readable.push (_stream_readable.js:111:10)
api_1             |     at TCP.onread (net.js:529:20)
```

**Comment by petkaantonov** [comment]
what ia __default__

**Comment by devotox** [comment]
```
function() {

		var return_code = { code: response_status.internal_success, message: 'Successful' };

		if(error) {
			console.error(addTimestamp(), '** HTTP RESPONSE ERROR - within function', calling_function, '|', error.code, ':', utils.get_error(error), '\n');
			return_code = { code: response_status.internal_error, message: utils.get_error(error) };
			return seneca_done( null, { status: return_code, result: null } );
		}

		if (_.isFunction(__callback__)) {
			result = __callback__(result, model_version) || result;
		}

		if(result && (result.__continue__) ) {
			return;
		}

		promise.resolve(result).then(function(result){
			if(result && (result.__empty__ || result.__continue__) ) {
				var _code = result.code || response_status.internal_success;
				return_code = { code: _code, message: result.message || 'No Records Found.' };
				return seneca_done( null, _.merge({ status: return_code, result: result.response || null }, result.http_response || {}));
			}

			if(!result || !result.rows || !_.size(result.rows)) {
				return_code = { code: response_status.internal_error, message: 'HTTP endpoint returned no results' };
				console.error(addTimestamp(), '** HTTP RESPONSE ERROR - HTTP endpoint returned no results - within function', calling_function, '\n');
			}

			return seneca_done(null, { status: return_code, result: ( result && result.rows ) || result });
		}).catch(function(error){
			return_code = { code: response_status.internal_error, message: 'Unknown error occured ' + ( error && error.message ) || error };
			console.error(addTimestamp(), '** HTTP RESPONSE ERROR - unknown error occured - within function', calling_function, ( error && error.message ) || error, '\n');
			return seneca_done(null, { status: return_code, result: null });
		});
	};
```

I have tried returning the promise.resolve in default but same error

**Comment by devotox** [comment]
I have returned every promise.resolve to see if that is the issue but it has seemed to not change anything... could a timer i have be an issue in this

```
exports.log_seneca_request = function(level, args, return_code, procedure_name, calling_function, execution_time, result, error, error_code) {

	promise.resolve(true).then(function() {

		var seneca_identifier = _.filter(
			[ ].concat(
				[ args['action'], args['attribute'], args['data'] ],
				[ args['for'], args['from'], args['with'], args['via'], args['by'], args['as'] ]
			), function(value){ return !!value; }
		).join('-');

		if(args.data === 'logging') { return; }

		return seneca_identifier;

	}).then(function(seneca_identifier){
		if(!seneca_identifier) { return; }
		process.nextTick(function(){
			global.logger[level || 'info']('Seneca Request Log', {
				seneca_function: 'log_seneca_request',
				seneca_data: {
					seneca_identifier: seneca_identifier,
					calling_function: calling_function,
					procedure_name: procedure_name,
					execution_time: execution_time,
					return_code: return_code,
					error_code: error_code,
					result: result,
					error: error
				}
			});
		});
	}).catch(function(error){
		return console.error('** API LOG ERROR ** - Error Logging Seneca Request:', ( error && error.message ) || error);
	});
};
```

**Comment by petkaantonov** [comment]
You need to return the promise from \_\_default\_\_, additionaly the caller needs to returned the returned promise to its caller and so on. It is likely that you have an actual bug if you see this warning in 3.3.4.

**Comment by devotox** [comment]
I have now returned all promises within the full file and yet same thing

https://gist.github.com/devotox/809ea6d9711d1f330091

I have pasted the full file and error there as i cannot see anywhere else to return from

**Comment by devotox** [comment]
If it is too long to look at i can cut out the pieces i think is relevant ... but everywhere there is a promise.resolve i have made sure to return it

**Comment by petkaantonov** [comment]
Is the seneca.js framework promise-aware? If you are calling seneca from a promise handler and seneca calls your functions that returns promises but doesn't return them to the original call, then that would explain it.

**Comment by devotox** [comment]
No highly doubt it is. What would be the best way to go about fixing this so it doesnt care about the seneca framework

**Comment by petkaantonov** [comment]
You can disable the warning with Promise.config or environment variable `BLUEBIRD_W_FORGOTTEN_RETURN=0`

**Comment by devotox** [comment]
Thank you will do
