### ISSUE TITLE
Benchmark for streamline broken

### ISSUE THREAD

**Issue by gsathya** [petkaantonov/bluebird#1094]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
HEAD @ c0d4472cecd523c2f9d4805a23d87be3cfe03b41

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Platform info:
Linux 3.13.0-85-generic x64
Node.JS 6.1.0
V8 5.0.71.35

3) Did this issue happen with earlier version of bluebird?
N/A
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Steps to reproduce --
1) git clone bluebird
2) npm install
3) ./bench doxbee

Stack trace --

```
benchmarking ./doxbee-sequential/streamline-callbacks.js
module.js:440
    throw err;
    ^

Error: Cannot find module 'streamline/lib/callbacks/runtime'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/google/home/gunasekaran/code/bluebird/benchmark/doxbee-sequential/streamline-callbacks.js:1:140)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
benchmarking ./doxbee-sequential/streamline-generators.js
module.js:440
    throw err;
    ^

Error: Cannot find module 'streamline/lib/generators/runtime'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/google/home/gunasekaran/code/bluebird/benchmark/doxbee-sequential/streamline-generators.js:1:144)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

```
➜  bluebird git:(master)   ls benchmark/doxbee-sequential/streamline*
benchmark/doxbee-sequential/streamline-callbacks.js  benchmark/doxbee-sequential/streamline-generators.js  benchmark/doxbee-sequential/streamline._js
```

**Comment by benjamingr** [comment]
Ping @bjouhier

**Comment by bjouhier** [comment]
Thanks for pinging me. Dependencies changed when streamline got upgraded for babel. I'll fix.
