### ISSUE TITLE
.finally not a function, but .then still works in its place

### ISSUE THREAD

**Issue by 1mike12** [petkaantonov/bluebird#1164]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.4.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
windows 10 x64 , node 4.4.5
3) Did this issue happen with earlier version of bluebird?
never used an earlier version

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
``` stack 
c:\Users\1mike12\WebStormProjects\myproject\modules\exception-handler.js:15
        .finally(function(){
                ^

TypeError: Logger.errorP(...).then(...).catch(...).finally is not a function
    at process.<anonymous> (c:\Users\1mike12\WebStormProjects\myproject\modules\exception-handler.js:15:17)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)

Process finished with exit code 7
```
I have a chain of promises that seem to be working fine except for finally. 
`Logger.errorP(...).then(...).catch(...).finally()` 

but if I use a then() at the end, it still works 
`Logger.errorP(...).then(...).catch(...).then()`

What the chain looks like. .Basically I have a text sent to me, and a log made in the winston module, before exiting. I'm throwing a test error

``` javascript
//logger
var Logger = new (winston.Logger)({
    transports: [
        new winston.transports.BookshelfTransport({
            model: Log,
            timestamp: timestampFunction,
        }),

        new winston.transports.File({
            filename:"_logs/main.log",
            json: false,
            timestamp: timestampFunction
        }),

        new winston.transports.Console({
            timestamp: timestampFunction,
            colorize: true
        })
    ],
});

Logger.logP = function(level, message, meta){
    return new Promise(function(resolve, reject){
        Logger.log(level, message, meta, function(e, lvl, msg, mta){
            if (e){
                return reject(e);
            }
            resolve();
        })
    })
};

Logger.errorP = function(message, meta){
    return Logger.logP("error", message, meta);
};

//alert
module.exports = new function(){
    var self = this;

    self.alert = function(message){
        var emailAddress = myPhoneNumber + "@tmomail.net";
        var subject = "ebay bot";

        return self.sendEmail(emailAddress, subject, message)
    };

//actual usage 
process.on('uncaughtException', function (er) {
    Logger.errorP(er.message, {stack: er.stack})
        .then(function(){
            return AlertService.alert(er.message)
        })
        .catch(function(e){
            console.log("something went wrong in the exception handler" + e);
            return AlertService.alert(e.message)
        })
        .finally(function(){
            process.exit(1);
        })
});
```

**Comment by benjamingr** [comment]
That's a native promise - when you do new Promise be sure to do `var Promise = require("bluebird")` at the top

**Comment by 1mike12** [comment]
ah... thanks @benjamingr
