### ISSUE TITLE
Maximum callstack exceeded with coroutine

### ISSUE THREAD

**Issue by jeffijoe** [petkaantonov/bluebird#1193]
Bluebird 3.4.1, Node 6.2.2

```js
const Promise = require('bluebird')

const thing = Promise.coroutine(function*() { return true})
Promise.coroutine(function *() {
  for (let i = 0; i < 10000; i++) {
    yield thing()
  }

  return yield Promise.resolve(42)
})().then((r) => console.log('Done', r))
```

The for-loop is causing the overflow. If you lower the iteration count to like 1000 then it won't occur.

```
RangeError: Maximum call stack size exceeded
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:138:28)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
    at PromiseSpawn._promiseFulfilled (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:99:10)
    at PromiseSpawn._continue (G:\Projects\skyclip-api\node_modules\bluebird\js\release\generators.js:175:18)
```

I discovered this while using Babel's `transform-async-to-module-method`.

**Comment by calebboyd** [comment]
Looks like this has already been fixed!
https://github.com/petkaantonov/bluebird/issues/1170

**Comment by petkaantonov** [comment]
duplicate a
