### ISSUE TITLE
Warning promise gives wrong file/line

### ISSUE THREAD

**Issue by Alex-Werner** [petkaantonov/bluebird#1260]
Using "bluebird": "^3.4.1", on node v6.3.1, I had a warning about promise not returned. 
That's okay, but the Warning tell me that : 

```
(node:33144) Warning: a promise was created in a handler at domain.js:293:12 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (D:\Projects\giraf-back\node_modules\bluebird\js\release\promise.js:77:14)` 
```

Which is not a file in my project (I assume it belong to node). 
If I now go in debuggability line 441 in release (or see [here the file:line in the bluebird repo](https://github.com/petkaantonov/bluebird/blob/3746b7eca90dd8b11af73db5d30cf46d7dd90f9b/src/debuggability.js#L449) ), by removing the break, I can see the proper location 

```
(node:34872) Warning: a promise was created in a handler at D:\Projects\giraf-back\databases\MongoDB\collection.js:77:12 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (D:\Projects\giraf-back\node_modules\bluebird\js\release\promise.js:77:14)
```

This is what I have by default (eg: not removing the break), if I display the stacktrace (by adding console.log(stack) between [L440 and L441](https://github.com/petkaantonov/bluebird/blob/3746b7eca90dd8b11af73db5d30cf46d7dd90f9b/src/debuggability.js#L440)). 

```
[ '    at Collection.insert (D:\\Projects\\giraf-back\\databases\\MongoDB\\collection.js:77:12)',
  '    at D:\\Projects\\giraf-back\\models\\request.js:10:30',
  '    at bound (domain.js:280:14)',
  '    at runBound (domain.js:293:12)',
  '    at runCallback (timers.js:570:20)',
  '    at tryOnImmediate (timers.js:550:5)',
  '    at processImmediate [as _immediateCallback] (timers.js:529:5)' ]
(node:36620) Warning: a promise was created in a handler at D:\Projects\giraf-back\databases\MongoDB\collection.js:77:12 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (D:\Projects\giraf-back\node_modules\bluebird\js\release\promise.js:77:14)
```

**Comment by lecstor** [comment]
I'm getting the same from bluebird@3.4.6 on node 6.9.1
```
[ '    at addLinks (/usr/src/docca-pdf-server/node_modules/docca-pdf-document/lib/render/index.js:185:29)',
  '    at renderImage.then (/usr/src/docca-pdf-server/node_modules/docca-pdf-document/lib/render/index.js:204:7)',
  '    at bound (domain.js:280:14)',
  '    at runBound (domain.js:293:12)',
  '    at runCallback (timers.js:637:20)',
  '    at tryOnImmediate (timers.js:610:5)',
  '    at processImmediate [as _immediateCallback] (timers.js:582:5)' ]
(node:29) Warning: a promise was created in a handler at domain.js:293:12 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.each (/usr/src/docca-pdf-server/node_modules/bluebird/js/release/each.js:24:12)
```

**Comment by vachi** [comment]
getting the same issue as well 
```
(node:15560) Warning: a promise was created in a handler at domain.js:293:12 but was not returned from it, see http://goo.gl/rRqMUw
at Function.Promise.attempt.Promise.try (/Users/blah/blah/node_modules/bluebird/js/release/method.js:29:9)
```

**Comment by Alex-Werner** [comment]
Shouldn't it be better to well, just display the full stacktrace ?

**Comment by vachi** [comment]
sorry don't have a full stack trace :( its not an environment i have control over

**Comment by jellymann** [comment]
I'm getting the same warning messages, and it's pretty much impossible to track down where my leaky promises are when I don't have LOC to track them down with. It's very difficult scouring through 184269 lines of JS!

**Comment by petkaantonov** [comment]
Seems like a bug, doesn't look like those lines should be removed by cleanStack

**Comment by Alex-Werner** [comment]
I've test it. This is what cleanStack(traceLines) returns me.

![image](https://cloud.githubusercontent.com/assets/5849920/21809673/0885233c-d749-11e6-998c-4c880a34e8d1.png)
 

So i'm not sure it's a problem from cleanStack but instead going further I found that : 
![image](https://cloud.githubusercontent.com/assets/5849920/21809775/6742a124-d749-11e6-89f1-a6470698386d.png)

In fact, I can fix it by removing traceLines[i - 1] and replacing it by traceLines[i]

![image](https://cloud.githubusercontent.com/assets/5849920/21809878/d8b5d36c-d749-11e6-808e-63db44200be9.png)


I've fix it doing so : 
![image](https://cloud.githubusercontent.com/assets/5849920/21809931/13ee685e-d74a-11e6-8b6e-b28b9c966789.png)
I **added** a conditionnal verification of traceLines[i] and keep the original lines (I'm not sure, but I think there is sometimes where this gaves the good answer ?)

**Comment by AnyhowStep** [comment]
Just ran into this problem. Such is life =/
