### ISSUE TITLE
Cancelling long promise chains ends up in RangeError

### ISSUE THREAD

**Issue by ncortines** [petkaantonov/bluebird#1293]
node version: 6.5.0
bluebird version: 3.4.6
stack trace:

`/app/node_modules/bluebird/js/release/debuggability.js:347 Uncaught RangeError: Maximum call stack size exceeded
    at Promise.cancellationOnCancel [as _onCancel] (/app/node_modules/bluebird/js/release/debuggability.js:347:30)
    at Promise._invokeOnCancel (/app/node_modules/bluebird/js/release/cancel.js:113:33)
    at Promise._cancelBy (/app/node_modules/bluebird/js/release/cancel.js:52:14)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:14:22)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)
    at Promise.break.Promise.cancel (/app/node_modules/bluebird/js/release/cancel.js:26:37)`

**Comment by benjamingr** [comment]
Can you try with long stack tracdes enabled?

**Comment by ncortines** [comment]
That kills my application :)

**Comment by ncortines** [comment]
This code should reproduce the problem:

```
const wait = howLong => new Promise(r => setTimeout(r, howLong));
let promise;
let count = 0;
const test = () => {
    count++;
    if (count === 200000) {
        wait(0)
            .then(() => promise.cancel())
    }
    return Promise.resolve()
        .then(() => wait(0))
        .then(() => {
            console.log(count)
            if (count !== 1000000) {
                return test();
            }
        });
};
promise = test()
    .finally(() => console.log('went ok'));
```

**Comment by ncortines** [comment]
The problems seems to be in the recursive **_cancel_** calls:

`promise._followee().cancel();`

Making use of ES6 tail call optimization should resolve this issue.

**Comment by spion** [comment]
Sounds like a bug, recursion cannot be used to cancel "followees" because it fails on long promise chains.

**Comment by petkaantonov** [comment]
Yeah this needs to be rewritten as loop

https://github.com/petkaantonov/bluebird/blob/master/src/cancel.js#L9-L39

**Comment by petkaantonov** [comment]
Something like this would be most straightforward :D:

```js

Promise.prototype["break"] = Promise.prototype.cancel = function() {
    if (!debug.cancellation()) return this._warn("cancellation is disabled");

    var stack = [];
    var promise = this;
    var child = promise;
    var parent = null;
    var line = 0;
    loop: while (promise._isCancellable() || stack.length > 0) {
        if (!promise._isCancellable()) {
            child = stack.pop();
            promise = stack.pop();
            parent = stack.pop();
            line = stack.pop();
        }

        if (line === 0 && !promise._cancelBy(child)) {
            if (child._isFollowing()) {
                stack.push(1);
                stack.push(parent);
                stack.push(promise);
                stack.push(child);
                line = 0;
                parent = null;
                promise = child._followee();
                child = promise;
                continue;
            } else {
                child._cancelBranched();
            }

            if (stack.length > 0) {
                continue;
            } else {
                break;
            }
        }

        switch (line) {
            case 0: parent = promise._cancellationParent; break;
            case 1: line = 0; continue loop;
            case 2: line = 0; continue loop;
            case 3: {
                line = 0;
                promise._setWillBeCancelled();
                child = promise;
                promise = parent;
                continue loop;
            }

        }

        if (parent == null || !parent._isCancellable()) {
            if (promise._isFollowing()) {
                stack.push(2);
                stack.push(parent);
                stack.push(promise);
                stack.push(child);
                line = 0;
                parent = null;
                promise = promise._followee();
                child = promise;
                continue;
            } else {
                promise._cancelBranched();
            }

            if (stack.length > 0) {
                continue;
            } else {
                break;
            }
        } else {
            if (promise._isFollowing()) {
                stack.push(3);
                stack.push(parent);
                stack.push(promise);
                stack.push(child);
                line = 0;
                parent = null;
                promise = promise._followee();
                child = promise;
                continue;
            }
            promise._setWillBeCancelled();
            child = promise;
            promise = parent;
        }
    }
    ASSERT(stack.length === 0);
};
```
