### ISSUE TITLE
Safari not showing proper stack traces.

### ISSUE THREAD

**Issue by gajewsk2** [petkaantonov/bluebird#1335]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
npm:bluebird@3.4.7
2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
    "node": "6.5.0",
    "npm": "3.10.3"
Issue only on Safari 8, I'm on 8.0.8. Haven't tested on any other version of safari.
3) Did this issue happen with earlier version of bluebird?
IDK
(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)
I'm attempting to log my promise errors. This works for Chrome and FF. 
```
console.es6:5 Unhandled promise rejection: Error: NSBridge timed out
    at eval (http://localhost:8000/static/scripts/base/cart/cart_data/ns-cart.model.es6.js:1005:21)
From previous event:
    at NsCartData._resolveInCart (http://localhost:8000/static/scripts/base/cart/cart_data/ns-cart.model.es6.js:1001:53)
    at eval (http://localhost:8000/static/scripts/base/cart/cart_data/ns-cart.model.es6.js:973:29)
From previous event:
    at NsCartData._adding (http://localhost:8000/static/scripts/base/cart/cart_data/ns-cart.model.es6.js:969:21)
    at NsCartData.add (http://localhost:8000/static/scripts/base/cart/cart_data/cart.model.es6.js:605:18)
    at AddToCart._add (http://localhost:8000/static/scripts/base/cart/widgets/add-to-cart.ctrl.es6.js:1165:19)
    at eval (http://localhost:8000/static/scripts/base/cart/widgets/add-to-cart.ctrl.es6.js:1076:21)
    at fire (http://localhost:8000/static/jspm_packages/npm/jquery@2.1.0/dist/jquery.js:3049:30)
    at Object.add [as done] (http://localhost:8000/static/jspm_packages/npm/jquery@2.1.0/dist/jquery.js:3095:7)
    at HTMLFormElement.eval (http://localhost:8000/static/scripts/base/cart/widgets/add-to-cart.ctrl.es6.js:1066:14)
    at HTMLFormElement.dispatch (http://localhost:8000/static/jspm_packages/npm/jquery@2.1.0/dist/jquery.js:4373:9)
    at HTMLFormElement.elemData.handle (http://localhost:8000/static/jspm_packages/npm/jquery@2.1.0/dist/jquery.js:4059:28)
    at HTMLFormElement.nrWrapper (http://localhost:8000/aqua-pure-wrench-for-ap801-ap801-c-wrench/i/G9173595/:391:28)
```

But for Safari shows this:

```
tryCatcher

tryCatcher
_settlePromiseFromHandler
_settlePromise
_settlePromise0
_settlePromises
_drainQueue
_drainQueues
drainQueues
PromiseResolutionHandlerFunction@[native code]
```

The handler looks like:
```
  window.addEventListener('unhandledrejection', (event) => {
    event.preventDefault(); // Prevents default handler (would log to console).
    let reason = event.detail.reason;
    console.error(reason && (reason.stack || reason));
  });
```

**Comment by petkaantonov** [comment]
safari stack traces are normally unhelpful like that

**Comment by benjamingr** [comment]
Yes, this is not a regression. There is no way we know of to get good stack traces in Safari.
