### ISSUE TITLE
TypeError: Cannot read property 'call' of null

### ISSUE THREAD

**Issue by bhauraobirajdar** [petkaantonov/bluebird#1356]
Hi Team,

I am calling three different function & doing some database operation, but I am getting this error.

If I tried with two functions, it is working but with three dunction it is throwing error,

here is error trace

TypeError: Cannot read property 'call' of null
    at FunctionDisposer.doDispose (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/using.js:98:18)
    at FunctionDisposer.Disposer.tryDispose (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/using.js:78:20)
    at iterator (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/using.js:36:53)
    at dispose (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/using.js:48:9)
    at /home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/using.js:194:20
    at PassThroughHandlerContext.finallyHandler (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/finally.js:55:23)
    at PassThroughHandlerContext.tryCatcher (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/bhaurao/Projects/Rules_work/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)

Bluebird version -- 3.5

Node Version -- v7.6.0

**Comment by benjamingr** [comment]
If you believe there is a bug, please show us minimal code to reproduce it - otherwise please ask on StackOverflow.

**Comment by bhauraobirajdar** [comment]
Hi,

I am giving three database request. Here here the code

This is main.js

var myModule = require('../lib/myModule');
var sync = require('deasync');

var id = 90;
var moduleObj = new moduleEntity(id);
console.log(moduleObj);

var id = 90;
var moduleObj = new moduleEntity(id);
console.log(moduleObj);

var id = 90;
var moduleObj = new moduleEntity(id);
console.log(moduleObj);

***********************************************************************************************************
In MyModule.js


var deasync = require('deasync');
var dbEntity = require('../db/dbEntity');

module.exports = function (id) {
    var outputEntity;
    dbEntity(id, function(data){
        outputEntity = data
    });
    while(outputEntity === undefined) { deasync.runLoopOnce();};
    return outputEntity;

};

*******************************************************************

In dbEntery.js


var Promise = require("bluebird");
var getConnection = require('./dbcon');

module.exports = function (id,cb) {
    var sql_getRecords = `SELECT * from tanle_name `;

    Promise.using(getConnection, function (conn) {
        return conn.query(sql_getRecords).then(function(data){
            cb(data[0]);
        })
    });
};

When I execute the main.js file then I get error that I given in my previous comment.

So After doing some analysis I got the file from which issue coming.

If you got to bluebird/js/release/using.js on line no 39 return thrower(e);

If I comment this line, then this issue is not coming & all is working fine. 

FOr now I have commented that line, but I dont think so, this is an permanent solution.
