### ISSUE TITLE
Exception while debugging on VS Code

### ISSUE THREAD

**Issue by sharma02gaurav** [petkaantonov/bluebird#1418]
The bluebird is throwing exception while debugging on VSCode.

Exception has occurred: Error
Error
    at Object.<anonymous> (***/node_modules/bluebird/js/release/util.js:378:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (***/node_modules/bluebird/js/release/promise.js:14:12)
    at Object.<anonymous> (***/node_modules/bluebird/js/release/bluebird.js:9:36)

**Comment by benjamingr** [comment]
Turn on long stack traces and show the error you get with them.

`Promise.config({longStackTraces: true})`

**Comment by sharma02gaurav** [comment]
I am not using bluebird... it's being used by some third party

**Comment by benjamingr** [comment]
You can set the appropriate environment variable instead then: http://bluebirdjs.com/docs/api/environment-variables.html

**Comment by jainmitesh09** [comment]
@sharma02gaurav @benjamingr Any resolution?

**Comment by sharma02gaurav** [comment]
@jainmitesh09 I don't know. It was a weird issue. Seems like package was broken or something. I re-clone my repository and installed dependency and after that It started working. Not a proper solution though but i don't know why?

**Comment by jainmitesh09** [comment]
@petkaantonov can you please update?

**Comment by jainmitesh09** [comment]
@sharma02gaurav turning off the breakpoints for all exceptions helps for now.

**Comment by jollifft** [comment]
Turning off all breakpoints also resolved the issue for me.

**Comment by edward12699** [comment]
if turnning off all breakpoints,,then debug is meanless,,,

**Comment by jollifft** [comment]
Sorry @edward12699 I didn't explain that very well. The issue was caused by me clicking "Debug -> Enable All Breakpoints". To resolve the issue, I clicked "Debug -> Disable All Breakpoints" and then manually enabled the breakpoints I needed one at a time. Hope this helps!

**Comment by jainmitesh09** [comment]
It took a while for me to get that too. Thanks @jollifft !

**Comment by maxgardner** [comment]
Ran into this as well and was able to use the skipFiles option in the debug config to ignore all packages:

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome

I like this because it still allows me to debug with all exceptions. Hope this helps anyone else who has found their way here.
