### ISSUE TITLE
UnhandledPromiseRejectionWarning appears even though rejection is caught

### ISSUE THREAD

**Issue by stieg** [petkaantonov/bluebird#1422]
I am on the fence if this is an error or not. Thought I would drop a line and see.

1) What version of bluebird is the issue happening on?

3.5.0

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)

node 8.1.4

3) Did this issue happen with earlier version of bluebird?

Unsure

Given the following code
```node
var bluebird = require('bluebird');
var util = require('util');

try {
  new Promise(function(resolve, reject) {
    return reject(new Error("effen err"));
  }).then(function(result) {
    console.log("SHOULD NOT SEE ME");
  }).catch(function(err) {
    console.log("Inner Catch", util.inspect(err));
  });
} catch (err) {
  console.log("Outer Catch", util.inspect(err));
}
```
I will receive the following output:
```
$ node bb-test.js
Inner Catch Error: effen err
    at /home/stieg/Devel/airfordable/afbeta/bb-test.js:6:19
    at Promise (<anonymous>)
    at Object.<anonymous> (/home/stieg/Devel/airfordable/afbeta/bb-test.js:5:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
This is all good and normal.  However if I add a `throw err` in my inner catch statement like so:
```node
var bluebird = require('bluebird');
var util = require('util');

try {
  new Promise(function(resolve, reject) {
    return reject(new Error("effen err"));
  }).then(function(result) {
    console.log("SHOULD NOT SEE ME");
  }).catch(function(err) {
    console.log("Inner Catch", util.inspect(err));
    throw err;                                                                                                                                                                                      
  });
} catch (err) {
  console.log("Outer Catch", util.inspect(err));
}
```
I will get the following:
```
$ node bb-test.js
Inner Catch Error: effen err
    at /home/stieg/Devel/airfordable/afbeta/bb-test.js:6:19
    at Promise (<anonymous>)
    at Object.<anonymous> (/home/stieg/Devel/airfordable/afbeta/bb-test.js:5:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
(node:27449) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: effen err
(node:27449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I would expect to receive the same error twice given the code above (one with the inner catch, one with the outer catch), however it does not seem to work like that.  Is this a broken expectation on my part?

**Comment by spion** [comment]
It looks like you're importing but not using bluebird? Try `var Promise = require('bluebird')`

**Comment by benjamingr** [comment]
When you rethrow the error it won't be caught synchronously - bluebird is warning you about this.

This is simply how control flows in JavaScript - if you want a synchronous catch to work with the promise chain use an async function.
