### ISSUE TITLE
.done() signifies a promise is handled; chains that end in it are not runaway promises

### ISSUE THREAD

**Issue by RoboPhred** [petkaantonov/bluebird#1491]
1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
NodeJS 8.9.1

3) Did this issue happen with earlier version of bluebird?
Unknown - new usage.

Currently, there seems to be no way for a library that wishes to use promises but expose a callback api without causing floods of false-positive runaway promise warnings if a consuming library then wraps those callbacks in other bluebird promises.

It seems the semantics of .done() indicate that the promise is absolutely at an end and fully handled, so we have been using it for promises that perform setup work inside things like streams, which communicate their readiness over EventEmitter events rather than exporting a promise.  As such, any promise chain in which all branches end in a .done() should not be considered a runaway promise error.

After a few minutes of experimentation, I was able to make a trial implementation of this in debuggability.js by calling this function from checkForgottenReturns against ```promiseCreated```
```
function checkEventuallyFinal(promise) {
    if (promise._isFinal()) return true;
    if (promise._promise0 && !checkEventuallyFinal(promise._promise0)) return false;
    var len = (promise._bitField & 65535);
    for(var i = 1; i < len; i++) {
        var child = promise._promiseAt(i);
        if (!checkEventuallyFinal(child)) return false;
    }
    return true;
}
```

I have tested this out against our existing code, and it reliably silences the error when the promises are fully handled and end in .done(), and still warn when it detects 'true' runaway promises.

If performance is an issue, a bit field could be added indicating if all children are final, and propagated on each .done() call.

**Comment by benjamingr** [comment]
Thanks for raising the issue :)

First of all - `.done` is deprecated and should not be used

> Currently, there seems to be no way for a library that wishes to use promises but expose a callback api without causing floods of false-positive runaway promise warnings if a consuming library then wraps those callbacks in other bluebird promises.

We have the `.asCallback` utility method for that:

```js
myPromiseReturningFn().asCallback(cb); // cb is a standard node callback
function callbackApi(cb) {
  promiseReturningFn().asCallback(cb);
}
```

**Comment by RoboPhred** [comment]
Hmm, this was the first thing I tried, and I still got the same warnings.  I ended up reasoning that asCallback did not mark the promise as final because it returns yet another promise itself.

I will investigate further.

**Comment by RoboPhred** [comment]
So it seems that in some cases, asCallback does suppress the warning, but it does not in others.

In my use case, I am using bluebird internally (as a third party dependency from amqplib).  I have an api that generates an EventEmitter to listen to messages, and it has a .close() event to shut down the listener.  The logic for establishing the exchange, queue, and consumers is complex with lots of branching, but promises make this painless.  The shutdown logic is also async, and to make matters worse, I have to hold on to and await the connection promise on close so I can handle cases where .close() is called before the connection is fully established.

In my example consumer, I call the factory function to get the EventEmitter inside a ```new Promise``` handler, and resolve with the emitter when the emitter emits a "connect" event.  I then try to shut it down with .close()

Here is a simple implementation of the above that will emit the warning:
```
const Promise = require("bluebird");
const EventEmitter = require("events");


function waitPromise() {
    return new Promise((accept) => {
        setTimeout(() => accept(), 1000);
    });
}


function createMyEmitterApi() {
    const emitter = new EventEmitter();

    // This does not emit the warning.
    const connectPromise = waitPromise().then(() => 42).asCallback((err, result) => {
        if (err) emitter.emit("error", err);
        else emitter.emit("connect");
        return null;
    });

    // Calling emitter.close() will emit the warning, even though
    //  we handle it with asCallback
    emitter.close = () => {
        connectPromise.then(c => {
            // Close logic here.
            return waitPromise();
        }).asCallback((err, result) => {
            if (err) emitter.emit("error", err);
            emitter.emit("close");
            return null;
        });
    };
    return emitter;
}


console.log("creating emitter");

const myConsumer = new Promise((accept, reject) => {
    const apiObj = new createMyEmitterApi();
    apiObj.once("connect", () => accept(apiObj));
});

myConsumer.then(r => {
    console.log("We got the emitter");
    return waitPromise(1000).then(() => r);
}).then(r => {
    console.log("Closing emitter");
    return r.close(); 
}).then(() => {
    console.log("closed");  
});
```

Using --trace-warnings, this is the output I get
```
creating emitter
test.js:39
We got the emitter
test.js:47
Closing emitter
test.js:50
(node:3324) Warning: a promise was created in a handler at c:\dev\git\baselayer\bl_servicebus_endpoint_amqp\test.js:51:14 but was not returned from it, see http://goo.gl/rRqMUw
warning.js:18
    at Promise.module.exports.Promise.then (c:\dev\git\baselayer\bl_servicebus_endpoint_amqp\node_modules\bluebird\js\release\promise.js:125:17)
    at EventEmitter.emitter.close (c:\dev\git\baselayer\bl_servicebus_endpoint_amqp\test.js:26:24)
    at myConsumer.then.then.r (c:\dev\git\baselayer\bl_servicebus_endpoint_amqp\test.js:51:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.<anonymous> (c:\dev\git\baselayer\bl_servicebus_endpoint_amqp\test.js:49:4)
    at Module._compile (module.js:632:14)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
closed
```

**Comment by RoboPhred** [comment]
Is the semantics of asCallback() to forward responsibility to the callback passed in?  If so, this should always suppress the error; the promise is going to be handled by the callback and bluebird can wash its hands of it.

At any rate, I am still seeing this warning with asCallback, so bluebird thinks the promise is not guaranteed to be handled.

Here is a distilled version of what a lot of our consuming code is doing that generates the warning:
```
const Promise = require("bluebird");
const EventEmitter = require("events");


function waitPromise() {
    return new Promise((accept) => {
        setTimeout(() => accept(), 1000);
    });
}


function createMyEmitterApi() {
    const emitter = new EventEmitter();

    // This does not emit the warning.
    const connectPromise = waitPromise().then(() => 42).asCallback((err, result) => {
        if (err) emitter.emit("error", err);
        else emitter.emit("connect");
        return null;
    });

    emitter.close = () => {
        // Calling emitter.close() and having a continuation will
        //  trigger the warning, despite the asCallback.
        connectPromise.then(c => {
            // Close logic here.
            return waitPromise();
        }).asCallback((err, result) => {
            if (err) emitter.emit("error", err);
            emitter.emit("close");
            return null;
        });
    };
    return emitter;
}


console.log("creating emitter");

const myConsumer = new Promise((accept, reject) => {
    const apiObj = new createMyEmitterApi();
    apiObj.once("connect", () => accept(apiObj));
});

function consumeThenClose() {
    return myConsumer.then(r => {
        console.log("We got the emitter");
        console.log("The consumer is now listening to the close event outside of the project chain.");
        r.on("close", consumerCloseHandler);

        return waitPromise(1000).then(() => r);
    }).then(r => {
        console.log("Closing emitter");
        // This is typically legal with our api, pre-bluebird.
        //  The close listener might be external to this promise chain.
        // close() does not return a promise; the consumer shouldn't even know
        //  that there are promises at play here.
        // The promise identified by the warning is fully handled with
        //  an asCallback on line 30, and the result is continued through
        //  the event emitter.
        r.close();

        // A return-null here would suppress the error, and is probably best practices anyway,
        //   but this promise is treated as a no-value object to wait on in the actual code.
    });
}

// Attaching a promise continuation to the result of this function triggers the warning
//  against r.close() on line 63
// If we did not attach the .then(), it would not error, 
consumeThenClose().then(() => {
    console.log("consumeThenClose() completed.");
});


function consumerCloseHandler() {
    console.log("api consumer has seen the emitter close.");
}
```


I have an api that returns an EventEmitter.  This EventEmitter uses bluebird for work in its constructor (which is continued by a "connect" event.), and for a .close() function (which emits a "close" event as the promise continuation).

These objects will often be created inside new Promise() call, which wires up a global close event handler and completes when the connect event is raised.  This is rather unorthodox, but these items are long-lived and intended to run indefinitely.  These promises are then stored in an array until the client receives a shutdown signal.
When signaled to close, the promises are waited on and .close() is called.  However, it is up to the global close handler to handle these, since we may also get close events if the remote end closes us.

I would like to avoid requiring the clients to ```return null``` from their promises whenever calling one of our api functions.  A lot of code already exists that would need to be changed, and the story of "fix it with return null" has so far ended up suppressing several legitimate runaway promises.


If asCallback is really contracted as marking the promise as handled, this is probably a bug.  Otherwise, I feel that there should be some other way of claiming responsibility of the promise's continuation.
(It's a shame done is deprecated, the semantics of "this is the final handler" seems to naturally fit this behavior).
