### ISSUE TITLE
Invalid application error

### ISSUE THREAD

**Issue by TheDroide** [petkaantonov/bluebird#1496]
While setting up a Node.js-app using "alexa-app" (which depends on bluebird) I keep getting this error. I am sorry for not being able to provide more detailed information, but I am clueless what this message means, as neither Google nor Stackoverflow provide any information about an "Invalid application"-exception.

Node.js version: 8.9.4
Bluebird version: 2.11.0

Stacktrace:
```
Unhandled rejection Error: Invalid application
    at Promise._rejectCallback (.../node_modules/bluebird/js/main/promise.js:472:22)
    at Object.ensureErrorObject (.../node_modules/bluebird/js/main/util.js:261:20)
    at Promise._settlePromiseFromHandler (.../node_modules/bluebird/js/main/promise.js:516:17)
    at Promise._settlePromiseAt (.../node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (.../node_modules/bluebird/js/main/promise.js:248:10)
    at Immediate.Async.drainQueues (.../node_modules/bluebird/js/main/async.js:15:14)
    at Async._drainQueue (.../node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (.../node_modules/bluebird/js/main/async.js:133:10)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Edit: This seems to be the snippet that causes this error, I can't figure out why though:

```
new Promise((resolve, reject) => {
    ...
  }).then(function(content) {
    ...
  }).catch(function(reason) {
    response.fail(reason);
  });
```

**Comment by TheDroide** [comment]
Not a Bluebird issue, rather an exception propagating through the Promise function.
