### ISSUE TITLE
Sequelize : Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by opichon** [petkaantonov/bluebird#1510]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 9.8.0

3) Did this issue happen with earlier version of bluebird?
3.5.0: yes

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

I am either deleting or saving model instances through sequelize, eg

```
User.destroy({ where: { id: id } })
.then(() => {})

var user = new User({...})
user.save()
.then(() => {})
```

and everytime I get the warning. I've tried adding `return null` in the `then` clause but that does absolutely nothing.

**Comment by benjamingr** [comment]
Can you post the actual stack trace?

**Comment by opichon** [comment]
```
(node:78735) Warning: a promise was created in a handler at /Users/olivier/projects/kinkao/api/auth/auth.js:19:16 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/olivier/projects/kinkao/api/node_modules/sequelize/node_modules/bluebird/js/release/method.js:29:9)
Executing (default): SELECT `id`, `username`, `password`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `kk_users` AS `User` WHERE `User`.`username` = 'sam@kinkao.co' LIMIT 1;
(node:78735) Warning: a promise was created in a handler at /Users/olivier/projects/kinkao/api/auth/oauth.js:34:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/olivier/projects/kinkao/api/node_modules/sequelize/node_modules/bluebird/js/release/method.js:29:9)
Executing (default): DELETE FROM `kk_oauth_access_tokens` WHERE `user_id` = 4
Executing (default): DELETE FROM `kk_oauth_refresh_tokens` WHERE `user_id` = 4
Executing (default): INSERT INTO `kk_oauth_refresh_tokens` (`id`,`user_id`,`client_id`,`token`,`created_at`,`updated_at`) VALUES (DEFAULT,4,'admin','924ca61c25b3268c2effa1ac8bc458afa24c5fc624d27e1705114860d7e68698','2018-03-18 13:46:14','2018-03-18 13:46:14');
Executing (default): INSERT INTO `kk_oauth_access_tokens` (`id`,`user_id`,`client_id`,`token`,`created_at`,`updated_at`) VALUES (DEFAULT,4,'admin','cb5e48ece561c498db73c854d39c6deafc9e2f68ecd3a7302dd404978c0ba9ba','2018-03-18 13:46:14','2018-03-18 13:46:14');
```

**Comment by benjamingr** [comment]
You're using `Promise.method` - can you post the code surrounding it?

**Comment by opichon** [comment]
I don't use `Promise.method` directly. I can see `sequelize` using it though. Here is the `Model.destroy` method from `sequelize`:

```
destroy(options) {
    options = _.extend({
      hooks: true,
      force: false
    }, options);

    return Promise.try(() => {
      // Run before hook
      if (options.hooks) {
        return this.constructor.runHooks('beforeDestroy', this, options);
      }
    }).then(() => {
      const where = this.where(true);

      if (this.constructor._timestampAttributes.deletedAt && options.force === false) {
        const attribute = this.constructor.rawAttributes[this.constructor._timestampAttributes.deletedAt];
        const field = attribute.field || this.constructor._timestampAttributes.deletedAt;
        const values = {};

        values[field] = new Date();
        where[field] = attribute.hasOwnProperty('defaultValue') ? attribute.defaultValue : null;

        this.setDataValue(field, values[field]);

        return this.constructor.QueryInterface.update(
          this, this.constructor.getTableName(options), values, where, _.defaults({ hooks: false, model: this.constructor }, options)
        ).then(results => {
          const rowsUpdated = results[1];
          if (this.constructor._versionAttribute && rowsUpdated < 1) {
            throw new sequelizeErrors.OptimisticLockError({
              modelName: this.constructor.name,
              values,
              where
            });
          }
          return _.head(results);
        });
      } else {
        return this.constructor.QueryInterface.delete(this, this.constructor.getTableName(options), where, _.assign({ type: QueryTypes.DELETE, limit: null }, options));
      }
    }).tap(() => {
      // Run after hook
      if (options.hooks) {
        return this.constructor.runHooks('afterDestroy', this, options);
      }
    });
  }
```

**Comment by benjamingr** [comment]
I'm not sure, can you open a ticket for sequelize? These warnings are usually dead on and indicate bugs - if you'd like it's also possible to turn the warning off - although that wouldn't be my first course of action.

**Comment by georgecrawford** [comment]
@opichon I'm seeing a similar problem (with Sequelize v3.30.4 - we're not currently in a position to upgrade). Did you raise a ticket with them, or find a fix for the Bluebird warning?

**Comment by petkaantonov** [comment]
Do you have the code from:

/Users/olivier/projects/kinkao/api/auth/auth.js:19:16

And



/Users/olivier/projects/kk/api/auth/oauth.js:34:21

?

Look at those lines in those files
