### ISSUE TITLE
deprecated Buffer in NodeJS 10.x

### ISSUE THREAD

**Issue by wormen** [petkaantonov/bluebird#1524]
```
at Function.Promise.fromNode.Promise.fromCallback (/progect/node_modules/bluebird/js/release/promise.js:177:9)
node:21910) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by benjamingr** [comment]
That's a problem with whatever fromCallback is wrapping here which looking at the full stack trace would show.

You can also run node with `--trace-warnings` to see.

**Comment by et** [comment]
@wormen - did you figure this out?

I get the following with `--trace-warnings`:

```
(node:87882) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at Array.<anonymous> (/Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:149:21)
    at /Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:171:21)
    at wrapCallSite (/Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:343:20)
    at /Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:378:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/Users/et/code/NeatCapitalOrg/notifications/node_modules/source-map-support/source-map-support.js:377:24)
    at Object.setBounds (/Users/et/code/NeatCapitalOrg/notifications/node_modules/bluebird/js/release/debuggability.js:677:42)
```

but I couldn't find any usage of `source-map-support` in this repo so I'm not sure how this is happening.

**Comment by wormen** [comment]
@et  in `nodejs 10+` the API changed in `Buffer`
https://nodejs.org/dist/latest-v10.x/docs/api/buffer.html

**Comment by wormen** [comment]
@et Unfortunately, no, I did not find

**Comment by benjamingr** [comment]
It was from `source-map-support` - it got fixed https://github.com/evanw/node-source-map-support/pull/212 - not sure what package you were using was using that.

Though note that Node.js should only warn if the usage is outside of node_modules so this is pretty odd.
