### ISSUE TITLE
TimeoutOverflowWarning on NodeJS 10.13.0

### ISSUE THREAD

**Issue by stefansaravolac** [petkaantonov/bluebird#1566]
Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
3.5.3

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Nodejs 10.13.0 on Linux OpenSuse

3) Did this issue happen with earlier version of bluebird?
Yes, it happened in 3.5.1, 3.5.2, 3.5.3 after nodejs was updated.

This warning started appearing after NodeJS version was updated from 8.9.0 to 10.13.0.
Please note that it does not affect execution of code.

`
(node:14343) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (internal/timers.js:59:15)
    at setInterval (timers.js:503:19)
    at fallback (/home/developer/project1/node_modules/async-listener/index.js:619:15)
    at /home/developer/project1/node_modules/async-listener/index.js:649:53
    at /home/developer/project1/Apps/DevTestApp/DevTestApp.js:230:13
    at /home/developer/project1/CorePublic.js:423:41
    at tryCatcher (/home/developer/project1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/developer/project1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/developer/project1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/developer/project1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/developer/project1/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/developer/project1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/developer/project1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/developer/project1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/developer/project1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
`

**Comment by benjamingr** [comment]
That looks like someone did a `.delay(Infinity)`, can we get reproducing code?

**Comment by stefansaravolac** [comment]
Hi, I've double checked my code after reading you comment. 
It's 100% my bad as I've added Number.POSITIVE_INFINITY in setTimeout to keep a test process alive.
Thanks.

**Comment by tanzeelDot064** [comment]
I have the same Timeoverflow issue please siggest me the solution
![image](https://user-images.githubusercontent.com/49426324/57355211-ef8c0c80-7186-11e9-9327-21538cbfe69c.png)
