### ISSUE TITLE
Cannot read property 'length' of undefined at windowCleaner

### ISSUE THREAD

**Issue by DanielHara** [petkaantonov/bluebird#1625]
1) What version of bluebird is the issue happening on?
    3.7.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
   Node 12.9.1, jsdom@11.12.0

3) Did this issue happen with earlier version of bluebird?
    Happens on upgrading from 3.7.0 to 3.7.1

Upgrading from 3.7.0 to 3.7.1 broke my tests:

```
TypeError: Cannot read property 'length' of undefined
      at windowCleaner (../../node_modules/jsdom/lib/jsdom/browser/Window.js:487:41)
      at windowCleaner (../../node_modules/jsdom/lib/jsdom/browser/Window.js:488:9)
      at Window.close (../../node_modules/jsdom/lib/jsdom/browser/Window.js:495:6)
```

**Comment by DanielHara** [comment]
I guess this has to do with this jsdom issue: https://github.com/jsdom/jsdom/issues/1636
