### ISSUE TITLE
At Promise fromNode fromCallback - a promise was created  but was not returned from it

### ISSUE THREAD

**Issue by mercteil** [petkaantonov/bluebird#1638]
(This issue tracker is only for bug reports or feature requests, if this is neither, please choose appropriate channel from http://bluebirdjs.com/docs/support.html)

Please answer the questions the best you can:

1) What version of bluebird is the issue happening on?
- 3.7.2

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
- Node 12, Heroku worker
- Using babel 7

3) Did this issue happen with earlier version of bluebird?
Locally there is no issue at all. I haven't known about this until I pushed to Heroku.

---

I am having this issue on Heroku:

```javascript 
2020-02-19T12:37:49.314100+00:00 app[worker.1]: (node:4) Warning: a promise was created in a handler at internal/process/task_queues.js:79:21 but was not returned from it, see http://goo.gl/rRqMUw
2020-02-19T12:37:49.314102+00:00 app[worker.1]:     at Function.Promise.fromNode.Promise.fromCallback (/app/node_modules/bluebird/js/release/promise.js:206:9)
```

Since it is pointing to the bluebird node_module directly I assume there might be an issue in the package. (Btw. in the lib at the pointed fromNode.fromCallback there is this weird indentation of a ternary). 

![image](https://user-images.githubusercontent.com/36293774/74843103-bd215980-532b-11ea-855e-c4c4f0851b93.png)

**Comment by benjamingr** [comment]
You have a promise somewhere you create in a `.then` but forgot to return. Turn on long stack traces and figure it out :]

In general, please open support requests according to http://bluebirdjs.com/docs/support.html

**Comment by jwalton** [comment]
See also: https://github.com/petkaantonov/bluebird/blob/808fdf8fce0cf4dbb1b95129607777a0cd53df36/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

I was just bitten by this, too.  Basically, in BlueBird you're never allowed to have a Promise chain that ends in `undefined`.  A little annoying if you actually *want* to return `undefined` from a Promise, but there we are.  The documentation seems to suggest that you need to actually create a promise inside a handler for the warning to appear, but this does not appear to always be the case.
