### ISSUE TITLE
TypeError: Converting circular structure to JSON with custom errors

### ISSUE THREAD

**Issue by grofit** [petkaantonov/bluebird#329]
After making a post on SO:

http://stackoverflow.com/questions/26076511/handling-multiple-catches-in-promise-chain/26077868#26077868

I went down the route of making custom error objects which seems a great idea in general, and here is an example of one:

```
function CannotFindDocumentError(message) {
    this.message = message;
    this.name = "CannotFindDocumentError";
    Error.captureStackTrace(this, CannotFindDocumentError);
}
CannotFindDocumentError.prototype = Object.create(Error.prototype);
CannotFindDocumentError.prototype.constructor = CannotFindDocumentError;
```

However after adding this and returning these errors in rejection i.e:

```
this.Execute = function(collection) {
        return new Promise(function(resolve, reject) {

            var documentCallback = function(err, doc) {
                if(err) { return reject(err); }
                if(!doc) { return reject(new CannotFindDocumentError("Cannot find user document for id: " + accountId)); }
                resolve(doc);
            };

            var query = { Id: new mongodb.ObjectID(accountId)};
            collection.findOne(query, documentCallback);
        });
    }
```

This gets consumed in other places and often bubbled up via something like:

```
.catch(reject);
```

So since adding this I keep getting the error:

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at <my-dir>\node_modules\mocha\lib\runnable.js:220:76
    at tryCatch1 (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (<my-dir>\node_modules\supertest-as-promised\node_modules\bluebird\js\main\async.js:37:14)
    at process._tickCallback (node.js:419:13)
```

Now I get the error is telling me that something is referencing itself within the object hierarchy, however I don't get what, and the errors are all internal to 3rd party libs, so I was wondering if I am doing something wrong here?

The main end point of the code looks like this:

```
repository.Query(getAccountByIdQuery)
            .then(convertDocumentToModel)
            .then(verifyOldPassword)
            .then(changePassword)
            .then(function(){
                res.status(200).send();
            })
            .catch(Data.Errors.CannotFindDocumentError,function(error) {
                console.log(error.message);
                res.status(404).send({ error: error.message });
            })
            .catch(Data.Errors.PasswordDoesNotMatchError, function(error) {
                console.log(error.message);
                res.status(406).send({ OldPassword: error.message });
            })
            .error(function(error){
                console.log(error);
                res.status(500).send({ error: "Unable to change password" });
            })
            .catch(function(error){
                console.log(error);
                res.status(500).send({ error: "Server Error" });
            });
```

In the test scenario I am confirming that a missing account results in 404, but it doesnt find the document, returns a custom error, then it should go to the correct catch and return the `error.message`, however it just seems to blow up once it gets the error...

**Comment by alexbooker** [comment]
@grofit Nice one.
