### ISSUE TITLE
Source Maps w/ Browserify

### ISSUE THREAD

**Issue by mattdesl** [petkaantonov/bluebird#363]
Currently can't get source maps working correctly with `Promise.method` and Browserify.

``` js
var Promise = require('bluebird')
Promise.longStackTraces()
var foo = Promise.method(function() {
    throw new Error("BLAH")
    return 200
})

foo()
```

Stack trace:

```
Possibly unhandled Error: BLAH
    at http://localhost:8000/js/bundle.js:8:11
    at tryCatch1 (http://localhost:8000/js/bundle.js:5082:21)
    at Promise$_method (http://localhost:8000/js/bundle.js:2184:25)
    at Object../tests/cocoon-app.js.bluebird (http://localhost:8000/js/bundle.js:13:1)
    at s (http://localhost:8000/js/bundle.js:1:254)
    at e (http://localhost:8000/js/bundle.js:1:425)
    at http://localhost:8000/js/bundle.js:1:443 
```

The error source-maps correctly without the `Promise.method` wrapper. Noticing the same with `Promise.promisify`.

**Comment by aldendaniels** [comment]
@mattdesl - so it looks like the source map URL isn't being turned into a link because source-map-support isn't including the page origin in the stack trace.

It's generating:
```
Unhandled rejection Error: oops!
    at Route.willTransitionTo [as onEnter] (components/outcomes-component.js:29:21)
```

Instead of:
```
Unhandled rejection Error: oops!
    at Route.willTransitionTo [as onEnter] (http://localhost:8080/components/outcomes-component.js:29:21)
```

A handy work around is to:
 1. Copy the location (e.g. `components/outcomes-component.js:29:21`) 
 2. Head over to the sources pane in Chrome
 3. `CMD+P`, then paste in the location and hit `ENTER`

Not as nice as a link, but better than manually hunting for the file/line offset.

**Comment by zallek** [comment]
I have the same issue, I can't make sourcemaps work, that's make debugging almost impossible ...

**Comment by stereokai** [comment]
Was this ever fixed? I'm having the same trouble with Bluebird v3.1.1
