### ISSUE TITLE
Throwing "self is not defined" for unhandled errors on node

### ISSUE THREAD

**Issue by grrowl** [petkaantonov/bluebird#478]
Any error thrown in my project results in "Fatal error: self is not defined". Adding a `Promise.onPossiblyUnhandledRejection` (in order to access the true underlying `error.stack`) or adding `.catch()` to the promise itself still results in this error. Node v0.10.33.

The file locations are due to source mapping (running on compiled code):
```
webpack:///./~/bluebird/js/main/captured_trace.js:229
        globalEventFired = fireGlobalEvent(name, reason, promise);
^
ReferenceError: self is not defined
    at webpack:///./~/bluebird/js/main/captured_trace.js:466:1
    at Function.CapturedTrace.fireRejectionEvent (webpack:///./~/bluebird/js/main/captured_trace.js:229:1)
    at Promise._notifyUnhandledRejection (webpack:///./~/bluebird/js/main/debuggability.js:30:1)
    at Async._drainQueue (webpack:///./~/bluebird/js/main/async.js:84:1)
    at Async._drainQueues (webpack:///./~/bluebird/js/main/async.js:91:1)
    at [object Object].Async.drainQueues [as _onTimeout] (webpack:///./~/bluebird/js/main/async.js:14:1)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by petkaantonov** [comment]
Is there are a reason you are using webpack module in node? Only npm module is supported in node.

**Comment by grrowl** [comment]
I'm using webpack as a transpiler (ES6 and JSX to plain JS to run within node), a glorified concatenator in this case, but it emits sourcemaps which leave references to itself. `webpack:///./~/bluebird/js/main/captured_trace.js` maps to `./node_modules /bluebird/js/main/captured_trace.js`. The browser build throws the same issue. I should metion this is on bluebird@2.9.5

```
webpack:///./~/bluebird/js/browser/bluebird.js:632
        globalEventFired = fireGlobalEvent(name, reason, promise);
^
ReferenceError: self is not defined
    at webpack:///./~/bluebird/js/browser/bluebird.js:869:1
    at Function.CapturedTrace.fireRejectionEvent (webpack:///./~/bluebird/js/browser/bluebird.js:632:1)
    at Promise._notifyUnhandledRejection (webpack:///./~/bluebird/js/browser/bluebird.js:1022:1)
    at Async._drainQueue (webpack:///./~/bluebird/js/browser/bluebird.js:136:1)
    at Async._drainQueues (webpack:///./~/bluebird/js/browser/bluebird.js:143:1)
    at [object Object].Async.drainQueues [as _onTimeout] (webpack:///./~/bluebird/js/browser/bluebird.js:66:1)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

I've updated the error in the first post, too. `self` never gets defined anywhere in `captured_trace.js`, which throws me.  Any thoughts?

**Comment by petkaantonov** [comment]
`self` is the global object in browsers and web workers (`window` doesn't work in a web worker so `self` is used as more general).

But anyway, `window` should be undefined in node, why is it not in your case? can you log `console.log(window)` to see what it is.

**Comment by grrowl** [comment]
Ah! Thanks so much for clearing that up -- turns out webpack was browser-ifying the environment during build (process became shimmed to an object, process.version became `undefined`, and window stayed undefined). 

Setting the [webpack configuration variable `node`](http://webpack.github.io/docs/configuration.html#node) to leave `process` alone (set to `false`) fixed the issue. Thanks again for your assistance.

**Comment by daniloprates** [comment]
Does anyone know how would I change this setting on Browserify? I'm getting the same error.

**Comment by nadavten** [comment]
@grrowl please explain and expand your solution solution

**Comment by grrowl** [comment]
In my `webpack.config.js`:

> Setting the [webpack configuration variable `node`](http://webpack.github.io/docs/configuration.html#node) to leave `process` alone (set to `false`) fixed the issue.
