### ISSUE TITLE
Unhandled rejection has stack trace in Chrome/FF but not IE11

### ISSUE THREAD

**Issue by rogierschouten** [petkaantonov/bluebird#536]
An unhandled rejection has a stack property in Chrome and FF but not in IE11, why is that? Uncaught exceptions do have stack traces in IE11.

Code:
```javascript
Promise.reject(new Error("test rejection"));
```

IE11:
```
stack:
```

Chrome:
```
stack:

Error: test rejection
    at Navigation.causeReject (http://127.0.0.1:8080/bundle.js:4812:24)
    at Object.executeDispatch (http://127.0.0.1:8080/bundle.js:26244:21)
    at SimpleEventPlugin.executeDispatch (http://127.0.0.1:8080/bundle.js:39018:40)
    at forEachEventDispatch (http://127.0.0.1:8080/bundle.js:26232:5)
    at Object.executeDispatchesInOrder (http://127.0.0.1:8080/bundle.js:26253:3)
    at executeDispatchesAndRelease (http://127.0.0.1:8080/bundle.js:25622:22)
    at forEachAccumulated (http://127.0.0.1:8080/bundle.js:41022:8)
    at Object.EventPluginHub.processEventQueue (http://127.0.0.1:8080/bundle.js:25827:5)
    at runEventQueueInBatch (http://127.0.0.1:8080/bundle.js:33418:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (http://127.0.0.1:8080/bundle.js:33444:5)
    at handleTopLevelImpl (http://127.0.0.1:8080/bundle.js:33530:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (http://127.0.0.1:8080/bundle.js:39992:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (http://127.0.0.1:8080/bundle.js:32157:19)
    at Object.batchedUpdates (http://127.0.0.1:8080/bundle.js:38158:20)
    at ReactEventListener.dispatchEvent (http://127.0.0.1:8080/bundle.js:33625:20
```

Firefox:
```
stack:

[23]</Navigation</Navigation.prototype.causeError@http://127.0.0.1:8080/bundle.js:4809:15
executeDispatch@http://127.0.0.1:8080/bundle.js:26244:21
[182]</</SimpleEventPlugin.executeDispatch@http://127.0.0.1:8080/bundle.js:39018:23
forEachEventDispatch@http://127.0.0.1:8080/bundle.js:26232:5
executeDispatchesInOrder@http://127.0.0.1:8080/bundle.js:26253:3
[105]</</executeDispatchesAndRelease@http://127.0.0.1:8080/bundle.js:25622:5
[213]</forEachAccumulated@http://127.0.0.1:8080/bundle.js:41022:5
[105]</</EventPluginHub.processEventQueue@http://127.0.0.1:8080/bundle.js:25827:5
runEventQueueInBatch@http://127.0.0.1:8080/bundle.js:33418:3
[148]</ReactEventEmitterMixin.handleTopLevel@http://127.0.0.1:8080/bundle.js:33444:5
handleTopLevelImpl@http://127.0.0.1:8080/bundle.js:33530:1
[194]</</Mixin.perform@http://127.0.0.1:8080/bundle.js:39992:13
[140]</ReactDefaultBatchingStrategy.batchedUpdates@http://127.0.0.1:8080/bundle.js:32157:7
batchedUpdates@http://127.0.0.1:8080/bundle.js:38158:3
[149]</ReactEventListener.dispatchEvent@http://127.0.0.1:8080/bundle.js:33625:7
```

**Comment by petkaantonov** [comment]
IE adds stack property to objects that are thrown, not to error objects in general

**Comment by rogierschouten** [comment]
Ok, I just submitted a bug to IE :)

https://connect.microsoft.com/IE/feedbackdetail/view/1192551/ie-does-not-add-stack-trace-to-error-object
