### ISSUE TITLE
Build fails on windows with CRLF line endings 

### ISSUE THREAD

**Issue by HenriKarapuu** [petkaantonov/bluebird#566]
tools/build.js throws if git or any editor changes the line endings to CRLF (which they often do by default on Windows). This makes working on bluebird codebase a hassle, as every tool and editor needs to be manually configured to use LF line endings just for bluebird. Should be simple to fix?

Unhandled rejection Error: The file F:\Projects\_Modified\JavaScript\bluebird\src\bind.js
contains an illegal character:
 (U+000D) on line 1 at column 14
    at noStackError (F:\Projects\_Modified\JavaScript\bluebird\tools\utils.js:11:13)
    at F:\Projects\_Modified\JavaScript\bluebird\tools\utils.js:26:23
    at Array.forEach (native)
    at Object.checkAscii (F:\Projects\_Modified\JavaScript\bluebird\tools\utils.js:18:30)
    at eval (eval at getTaskFunction (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:413:33), <anonymous>:5:27)
    at eval (eval at getTaskFunction (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:413:33), <anonymous>:4:31)
    at promise.then.finally.then.process.send.type (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:507:32)
    at process._tickCallback (node.js:419:13)
    at Object.actions.newTask (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:500:22)
    at Object._onImmediate (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:546:39)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
From previous event:
    at Object.ret.run (F:\Projects\_Modified\JavaScript\bluebird\tools\job-runner\job-runner.js:141:27)
    at F:\Projects\_Modified\JavaScript\bluebird\tools\build.js:317:30
From previous event:
    at F:\Projects\_Modified\JavaScript\bluebird\tools\build.js:316:32
    at process._tickCallback (node.js:419:13)
From previous event:
    at Module.build [as exports] (F:\Projects\_Modified\JavaScript\bluebird\tools\build.js:315:20)
    at Object.<anonymous> (F:\Projects\_Modified\JavaScript\bluebird\tools\build.js:365:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by petkaantonov** [comment]
This is intentional because people apparently ignore the `.editorconfig` file which also states that LF must be used.

FWIW all my editors on Windows use LF by default and this project has been developed mostly on windows, not sure why you would use CRLF as default.

**Comment by HenriKarapuu** [comment]
Moi Petka, thanks for your fast reply

I guess your choice makes sense if you've had badly behaving committers before and wan't to enforce the line endings. And yes, i wasn't aware of the .editorconfig file at all.

As for your question why using CRLF on windows: it is the 'native' line ending style for windows, the default of most windows editors, and the de-facto standard for .NET development, which i also do. By default Git checkout transforms the line endings automatically to CRLF and commit back to LF so the only hassle is to add step in build process that changes the line endings in output artefacts to LF if needed (but this isn't much more effort than it is to throw the current intentional exception).

**Comment by bergus** [comment]
I downloaded the repo today and tripped over this as well. What did help in the end was to add a `.gitattributes` file with the contents
```text
* eol=lf
```
(then I had to delete everything and checkout again). Maybe this should be commited?

**Comment by petkaantonov** [comment]
@bergus PR welcome
