### ISSUE TITLE
Illegal invocation when resolving a promise in nw.js (node-webkit)

### ISSUE THREAD

**Issue by analog-nico** [petkaantonov/bluebird#623]
I use the following code in nw.js:
``` js
(new BPromise(function (resolve) {
    resolve('test');
}))
    .then(console.log);
```

Or even simpler:
``` js
BPromise.resolve('test')
    .then(console.log);
```

Both snippets throw:
```
Unhandled rejection Error: TypeError: Illegal invocation
    at Object.ensureErrorObject (.../node_modules/bluebird/js/main/util.js:228:20)
    at Promise._rejectCallback (.../node_modules/bluebird/js/main/promise.js:416:22)
    at Promise._settlePromiseFromHandler (.../node_modules/bluebird/js/main/promise.js:460:17)
    at Promise._settlePromiseAt (.../node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (.../node_modules/bluebird/js/main/promise.js:224:10)
    at Async._drainQueue (.../node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (.../node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
```

I use Bluebird v2.9.25 and nw.js v0.12.1.

Any ideas?

**Comment by bergus** [comment]
You'll have to [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) the method to your object:

    Promise.resolve('test').then(console.log.bind(console))

See also https://stackoverflow.com/questions/25098385/why-does-passing-console-log-directly-to-promises-then-not-work

**Comment by analog-nico** [comment]
Oh indeed! Thanks @bergus !
