### ISSUE TITLE
Error Promisifying Library MongoSkin 

### ISSUE THREAD

**Issue by arj-196** [petkaantonov/bluebird#634]
var mongoskin = Promise.promisifyAll(require('mongoskin'));

Returns the error:

     h:\www\node_modules\bluebird\js\main\promisify.js:46
                    throw new TypeError("Cannot promisify an API that has norm
                          ^
    TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
    See http://goo.gl/iWrZbw

    at checkValid (h:\www\linkreaser_nodejs\node_modules\bluebird\js\main\promisify.js:46:27)
    at promisifiableMethods (h:\www\linkreaser_nodejs\node_modules\bluebird\js\main\promisify.js:69:5)
    at promisifyAll (h:\www\linkreaser_nodejs\node_modules\bluebird\js\main\promisify.js:230:9)
    at Function.Promise.promisifyAll (h:\www\linkreaser_nodejs\node_modules\bluebird\js\main\promisify.js:288:12)
    at Object.<anonymous> (h:\www\linkreaser_nodejs\modules\user_data.js:113:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
    Process finished with exit cod

**Comment by benjamingr** [comment]
Did you read the http://goo.gl link in the error message? Did you notice it?

**Comment by benjamingr** [comment]
Can you try:

```js
var mongoskin = Promise.promisifyAll(require("mongoskin"), {suffix: "P"});
```

This adds a `P` suffix instead of an `Async` one to the library.

**Comment by petkaantonov** [comment]
Cannot repro with latest mongoskin and 2.9.26:

```js
var Promise = require('bluebird');
var mongoskin = Promise.promisifyAll(require("mongoskin"));
// working just fine
```

mongoskin doesn't even have any methods with `Async` suffix

**Comment by arj-196** [comment]
@benjamingr I saw the link, and thats why i opened the issue as at the end it says "If you find this issue in a common library please open an issue".

**Comment by arj-196** [comment]
@petkaantonov @benjamingr  I can't seem to reproduce the error. Sorry guys. I think i wasted your time.
