### ISSUE TITLE
Issue using lodash's "_.partial" on function generated with ".promisifyAll()"

### ISSUE THREAD

**Issue by reggi** [petkaantonov/bluebird#714]
I'm getting a strange error when applying a partial on a promise. Not sure why this is happening. The tests [here](https://github.com/lodash/lodash/issues/1369) prove that it only occurs on a promise generated using bluebird's ".promisifyAll()" function.

I created an issue in lodash and I'm thinking I should create one here as well. 

https://github.com/lodash/lodash/issues/1369

Here's the stack trace for the issue.

```
TypeError: Cannot read property 'apply' of undefined
    at tryCatcher (/Users/thomas/Desktop/project/node_modules/bluebird/js/main/util.js:26:22)
    at ret (eval at <anonymous> (/Users/thomas/Desktop/project/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:11:39)
    at wrapper (/Users/thomas/Desktop/project/node_modules/lodash/index.js:3592:19)
    at Context.<anonymous> (/Users/thomas/Desktop/project/test/lodash-fsextra-partial.js:113:14)
    at callFn (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runnable.js:266:21)
    at Test.Runnable.run (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runnable.js:259:7)
    at Runner.runTest (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:390:10)
    at /Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:473:12
    at next (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:315:14)
    at /Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:325:7
    at next (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/Users/thomas/.nvm/versions/io.js/v2.2.1/lib/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by reggi** [comment]
Here's the code to produce the error:

```javascript
var Promise = require("bluebird")
var _ = require("lodash")

var lib = {}

lib.dummy = function(path, encoding, cb){
  return cb(null, "file content here")
}

Promise.promisifyAll(lib)

var readFile = _.partial(lib.dummyAsync, "path/hello.txt", "utf8")

readFile() // throws error
```

**Comment by benjamingr** [comment]
You're using lodash incorrectly. You're looking for `.bind` and not `_.partial`.

Here is a fixed example: http://jsfiddle.net/z1hgo3g5/

Please in the future ask support questions in the appropriate channels.

**Comment by reggi** [comment]
Thanks @benjamingr

**Comment by benjamingr** [comment]
Any time :)
