### ISSUE TITLE
Using mongoose with bluebird, I get unhandled rejections

### ISSUE THREAD

**Issue by awdogsgo2heaven** [petkaantonov/bluebird#773]
When using Mongoose with bluebird, every mongoose error prints 'Unhandled rejection ValidationError/WriteError' to the console. None of this information appeared until I started using bluebird, I'm not sure why it appears, and I've tried adding 'catches' at the end of my promises:
<code>var promise = Barcode.create({ barcode: barcode, standard: standard }).
    then(function(d) {});
    promise.catch(function(e){
        console.log(e);
          res.sendStatus(500);
    });
</code>
It successfully reaches the catch function, but it still prints this message anyways, should I be worried about these messages? and is there a way to turn them off if not?

**Comment by bergus** [comment]
Yes, you should be worried about them - some code is throwing exceptions that you didn't know about. Investigate where they came from - they should have long stack traces attached. If you've found the offending code, you might want to post to StackOverflow to get further help about fixing the problem - the github issue tracker is about bugs and feature requests.

**Comment by awdogsgo2heaven** [comment]
No I'm saying I have found them, and caught them using 'catch' function in bluebird, but they still output to the log. They are expected errors, and I need to handle them, and not have them print all over the console saying they are 'unhandled' when they are. As in the example code above, when I catch the area I print it to the terminal, in the output below, the error prints as expected, returns 500 error status but STILL prints as unhandled. 

Here is a print out example:

from console ------>>>>> { [ValidationError: Barcode validation failed]
  message: 'Barcode validation failed',
  name: 'ValidationError',
  errors: 
   { barcode: 
      { [ValidatorError: Invalid barcode]
        properties: [Object],
        stack: 'Error\n    at MongooseError.ValidatorError (/home/xxx/test/test-apps/node_modules/mongoose/lib/error/validator.js:25:16)\n    at validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:652:13)\n    at /home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:681:9\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:658:19)\n    at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1102:11\n    at process._tickCallback (node.js:355:11)',
        message: 'Invalid barcode',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'barcode',
        value: '668988' } } }
----Now saying unhandled after it was just caught---->>> Unhandled rejection ValidationError: Invalid barcode
    at MongooseError.ValidationError (/home/xxx/test/test-apps/node_modules/mongoose/lib/error/validation.js:22:16)
    at model.Document.invalidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1230:32)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1104:18
    at validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:653:7)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:681:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:658:19)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1102:11
From previous event:
    at model.Document.validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1071:10)
    at model.Object.defineProperty.value.fn (/home/xxx/test/test-apps/node_modules/mongoose/lib/schema.js:190:14)
    at model._next (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at model.proto.(anonymous function) [as $__original_save] (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:108:20)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1666:23
From previous event:
    at model.wrappedPointCut [as save] (/home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1648:14)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1634:37
    at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:570:21
    at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:249:17
    at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:46:24)
    at async.each (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:248:13)
    at Object.map (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:219:23)
    at _parallel (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:568:20)
    at Object.async.parallel (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:598:9)
    at /home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1640:11
From previous event:
    at Function.create (/home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1622:17)
    at exports.barcode (/home/xxx/test/test-apps/test-resource/api/discovery/discovery.controller.js:130:27)
    at Layer.handle [as handle_request] (/home/xxx/test/test-apps/test-resource/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/xxx/test/test-apps/test-resource/node_modules/express/lib/router/route.js:131:13)
    at next (/home/xxx/test/test-apps/node_modules/composable-middleware/lib/composable-middleware.js:40:9)
    at Query.<anonymous> (/home/xxx/test/test-apps/lib/auth/auth.service.js:36:9)
    at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:355:11)
        1) should return 422 for bad barcode

</code>

I hope the issue is more clear now.

**Comment by benjamingr** [comment]
Can you show us how you handle them (the code printing them)?

**Comment by awdogsgo2heaven** [comment]
All I do is catch all exceptions, print it, and respond with status 500. 

<code>var promise = Barcode.create({ barcode: barcode, standard: standard }); promise.catch(function(e){ console.log(e); res.sendStatus(500); }); </code>

**Comment by benjamingr** [comment]
Can you show us the code of Barcode.create? 

Doing:

    var promise = Promise.resolve(); // or Promise.delay
    promise.catch(function(e){

    });

Doesn't reproduce the behavior you describe so there has to be something else going on.

**Comment by benjamingr** [comment]
Closed by mistake, sorry.

**Comment by awdogsgo2heaven** [comment]
Hi, sorry for slow response, but the Barcode.create is  a mongoose Model.create. This issue happens for any model I create from. Their implementation can be found here: https://github.com/Automattic/mongoose/blob/master/lib/model.js, search 'Model.create'. I don't see them doing anything though abnormal. Just creates a new promise, calls the 'reject' handler when theirs an error.

**Comment by awdogsgo2heaven** [comment]
Issue was tracked down to be an issue in mongoose source and his been resolved: https://github.com/Automattic/mongoose/issues/3391.

Thanks!
