### ISSUE TITLE
Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by grawlinson** [petkaantonov/bluebird#826]
The 3.0.0 upgrade seems to have broken my web scraper. I get the following error message when trying to run [this](https://gist.github.com/grawlinson/1d6726f1626a72a1e270) code:

I've deleted the node_modules directory and reinstalled all modules, as well as creating a new project with barebones code. The issue still persists, but disappears after I roll back bluebird to v2.10.2.

````
Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]
    at apiRejection (<dir>/node_modules/bluebird/js/release/promise.js:10:27)
    at PromiseArray.init [as _init] (<dir>/node_modules/bluebird/js/release/promise_array.js:62:19)
    at Promise._settlePromise (<dir>/node_modules/bluebird/js/release/promise.js:546:21)
    at Promise._settlePromise0 (<dir>/node_modules/bluebird/js/release/promise.js:594:10)
    at Promise._settlePromises (<dir>/node_modules/bluebird/js/release/promise.js:677:18)
    at Promise._fulfill (<dir>/node_modules/bluebird/js/release/promise.js:618:18)
    at Request._callback (<dir>/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (<dir>/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (<dir>/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (<dir>/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
````

**Comment by spion** [comment]
promisify no longer makes multi-callback methods return arrays. This will break every single promisify call on `request` :(

**Comment by grawlinson** [comment]
It looks like I've got some reading & experimenting to do tonight. Thanks for letting me know.
