### ISSUE TITLE
Warning running server

### ISSUE THREAD

**Issue by speedingdeer** [petkaantonov/bluebird#928]
Hi

I've installed the latest and generated the project with sequalize (no mongodb). When I run server I get this warning. I can't figure out why. There is no new code on my side. Just the generated scaffold.

GET /api/things 304 9.731 ms - -
Warning: a promise was created in a handler but was not returned from it
    at executeSql (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/dialects/sqlite/query.js:96:19)
From previous event:
    at Promise.then (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/promise.js:21:17)
    at Database.<anonymous> (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/dialects/sqlite/query.js:258:14)
    at /Users/speedingdeer/code/lucy/node_modules/sequelize/lib/dialects/sqlite/query.js:91:19
From previous event:
    at [object Object].Query.run (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/dialects/sqlite/query.js:89:13)
    at /Users/speedingdeer/code/lucy/node_modules/sequelize/lib/sequelize.js:798:18
From previous event:
    at Promise.then (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/promise.js:21:17)
    at [object Object].Model.findAll (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/model.js:1369:6)
    at [object Object].Model.findOne (/Users/speedingdeer/code/lucy/node_modules/sequelize/lib/model.js:1490:34)
    at E4Store.get (/Users/speedingdeer/code/lucy/node_modules/express-sequelize-session/lib/e4store.js:51:29)
    at session (/Users/speedingdeer/code/lucy/node_modules/express-session/index.js:408:11)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:312:13)
    at /Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:271:10)
    at initialize (/Users/speedingdeer/code/lucy/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:312:13)
    at /Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/Users/speedingdeer/code/lucy/node_modules/cookie-parser/index.js:68:5)
    at Layer.handle [as handle_request] (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/speedingdeer/code/lucy/node_modules/express/lib/router/index.js:312:13)

**Comment by TheElrood** [comment]
Hi, same issue.

**Comment by benjamingr** [comment]
@mickhansen please advise. Why do you need the `new Promise` here? https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L96 

Nesting `new Promise` is almost never a great idea in my opinion but I'm not sure I understand the use case very well.

**Comment by benjamingr** [comment]
Here for example:

https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query.js#L252-L265

Couldn't it be an array map?

**Comment by mickhansen** [comment]
`new Promise` is not strictly, i don't recall the conversion exactly but we simply wanted to get away from event emitter quickly.

Ideally the code should be promisified yes. Why would `new Promise` trigger the return handler warning though?

**Comment by benjamingr** [comment]
I'm not sure - @petkaantonov  ?

**Comment by petkaantonov** [comment]
The warning is triggered by being in a handler and not returning anything while at the same time a promise is created anywhere in same turn

**Comment by mickhansen** [comment]
Hm alright, i'll have to test out changing stuff to promisification.
Eitherway this issue should be closed, not a bluebird issue.
